name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-latest     
      
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
      
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:21.10 \
              bash -exc 'apt-get update && \
              deactivate'
 
